#! /bin/bash 
if type -t wevtutil &> /dev/null 
then
    OS=MSWin
elif type -t scutil &> /dev/null 
then 
    OS=macOS
else
    OS=Linux
fi
echo $OS 

function is_alive_ping() { 
    ping -c 1 $1 > /dev/null 2>&1
    [ $? -eq 0 ] && echo "Node with IP: $i is up."
}
prueba=$(<ips.txt)
for i in $prueba 

do
firstport=79 
lastport=80
function portscan { 
for ((counter=$firstport; counter<=$lastport; counter++)) 
do 

	(echo >/dev/tcp/$i/$counter) > /dev/null 2>&1 && echo "$i $counter open" 
	
done 
}

is_alive_ping $i & disown 

done
portscan 
